image: Visual Studio 2019

branches:
  only:
  - master

environment:
  COVERALLS_REPO_TOKEN:
    secure: /PiLU85LQXTHDu9M30CGO9EWzNHjxuSD3SbP3wgMDaHFswAttPEOQ9OFzdlKEKhF

before_build:
  - ps: dotnet restore RDFSharp.sln

build_script:
  - ps: dotnet build -c Release RDFSharp.sln
  
test_script:
  - ps: dotnet test --collect:"XPlat Code Coverage" -c Release RDFSharp.Test\RDFSharp.Test.csproj
